# When a PR is merged into the main branch, this workflow opens a PR against the release branch
# with the squashed commit that went into main.

name: ðŸ’ Cherry pick into release PR

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  cherry-pick-into-release-pr:
    name: ðŸ’ Cherry pick into release PR
    runs-on: ubuntu-latest
    # Don't cherry pick things that are breaking.
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'release:feature-breaking') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # doesn't handle multiple authors...
      # - run: |
      #     authorName="$(gh api ${{ github.pull_request.commits_url }} -q .[0].commit.author.name)"
      #     authorEmail="$(gh api ${{ github.pull_request.commits_url }} -q .[0].commit.author.email)"
      #     echo 'AUTHOR='"$authorName $authorEmail" >> $GITHUB_ENV

      #     committerName="$(gh api ${{ github.pull_request.commits_url }} -q .[0].commit.committer.name)"
      #     committerEmail="$(gh api ${{ github.pull_request.commits_url }} -q .[0].commit.committer.email)"
      #     echo 'COMMITTER='"$committerName $committerEmail" >> $GITHUB_ENV

      - name: Cherry pick into release PR
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.2
        with:
          # We specify a token because we want other workflows (like CI) to run on this PR.
          # If we omit this, it uses the default token (GITHUB_TOKEN) which doesn't trigger other workflows.
          token: ${{ secrets.JTOAR_TOKEN }}
          branch: release
          labels: cherry-pick
          # author: ${{ process.env.AUTHOR }}
          # committer: ${{ process.env.COMMITTER }}
